development:
  adapter: postgresql
  database: <%= ENV['APPNAME_DATABASE_D'] %>
  username: <%= ENV['APPNAME_DATABASE_D_USER'] %>
  password: <%= ENV['APPNAME_DATABASE_D_PASSWORD'] %>
  host: localhost
  encoding: unicode

#production:
#  adapter: postgresql
#    database: <%#= ENV['APPNAME_DATABASE_P'] %>
#    username: <%#= ENV['APPNAME_DATABASE_P_USER'] %>
#    password: <%#= ENV['APPNAME_DATABASE_P_PASSWORD'] %>
#    host: localhost
#    encoding: unicode
