development:
  adapter: postgresql
  database: <%= ENV['APPNAME_DATABASE_D'] %>
  username: <%= ENV['APPNAME_DATABASE_D_USER'] %>
  password: <%= ENV['APPNAME_DATABASE_D_PASSWORD'] %>
  host: localhost
  encoding: unicode

test:
  adapter: postgresql
  database: <%= ENV['APPNAME_DATABASE_T'] %>
  username: <%= ENV['APPNAME_DATABASE_T_USER'] %>
  password: <%= ENV['APPNAME_DATABASE_T_PASSWORD'] %>
  host: localhost
  encoding: unicode

production:
  adapter: postgresql
  database: <%= ENV['APPNAME_DATABASE_P'] %>
  username: <%= ENV['APPNAME_DATABASE_P_USER'] %>
  password: <%= ENV['APPNAME_DATABASE_P_PASSWORD'] %>
  host: localhost
  encoding: unicode
